### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by am548726** [Valerie-Wissenburg/precision-skateboard#1]
# Semantics
## Naming Conventions
- Uhmm you guys broke this website https://gsnedders.html5.org/outliner/ when I was checking the document outline so I looked and you guys have a h1 and a h3 but no h2. So to fix this is to properly add your heading levels to where they apply in your website. Also you have javascript nested in your html and I think this is what caused the website to give me a error.
- Since you guys are using placeholder images when it comes to actually using real ones it would be best to name them for example hero-lg-skateboard.jpg or icon-lg-facebook.svg to easily search and find them in your folder.
- Lastly, to make it easy to tell what is nested you should format your code to easily identify what is what.

**Comment by MatthewCThompson** [comment]
On the topic of css classes, there was some that i got confused on. Unless the class was brought in, I didn't understand what "bottom" or "fi-shield" was doing. I would recommend giving these classes more meaning, for example, "fi-shield" could be "link-icon".
